# Justfile — task runner for the FocalPoint project
# See https://just.systems/man/en/

set dotenv-load

_default:
    @just --list

# Run all CI checks locally
ci: fmt-check lint test build
    @echo "✓ CI checks pass"

# Format code
fmt:
    cargo fmt --all

# Check formatting
fmt-check:
    cargo fmt --all -- --check

# Lint
lint:
    cargo clippy --all-targets --all-features -- -D warnings

# Run tests
test:
    cargo test --all-features

# Build release
build:
    cargo build --release

# Audit dependencies for security advisories
audit:
    cargo deny check advisories

# Check licenses
licenses:
    cargo deny check licenses

# Clean build artifacts
clean:
    cargo clean

# Grade targets (strictest checks — no caching)
grade:
    @echo "=== Running full grade ==="
    ./grade.sh

grade-fast:
    @echo "=== Running fast grade ==="
    ./grade.sh --fast

grade-json:
    @echo "=== Running grade (JSON) ==="
    ./grade.sh --json

grade-html:
    @echo "=== Running grade (HTML) ==="
    ./grade.sh --html

# Coverage — generate line coverage report (text) using cargo-llvm-cov
# DAG Stage 3 (QA Hardening): baseline measurement recipe
coverage:
    @echo "=== Generating line coverage report ==="
    cargo llvm-cov --workspace --all-features --summary-only

# Coverage — generate full HTML report under target/llvm-cov/html/
coverage-html:
    @echo "=== Generating HTML coverage report ==="
    cargo llvm-cov --workspace --all-features --html --output-dir target/llvm-cov/html
    @echo "Report: target/llvm-cov/html/index.html"

# Coverage — enforce the baseline threshold (currently 85% lines, per grade.sh)
coverage-check:
    @echo "=== Checking coverage against baseline threshold ==="
    cargo llvm-cov --workspace --all-features --fail-under-lines 85

# Coverage — record the current coverage snapshot as the baseline
# Writes docs/reference/coverage_baseline.md and target/llvm-cov/baseline.json
coverage-baseline:
    @echo "=== Recording coverage baseline ==="
    mkdir -p target/llvm-cov docs/reference
    cargo llvm-cov --workspace --all-features --summary-only --json --output-path target/llvm-cov/baseline.json
    @just _coverage-snapshot-md target/llvm-cov/baseline.json > docs/reference/coverage_baseline.md
    @echo "Baseline written to docs/reference/coverage_baseline.md"

# Coverage — clean all coverage artifacts
coverage-clean:
    rm -rf target/llvm-cov

# Internal: render a baseline snapshot markdown from a cargo-llvm-cov --json output
_coverage-snapshot-md json_path:
    @echo "# FocalPoint — Coverage Baseline Snapshot"
    @echo ""
    @echo "> Generated by \`just coverage-baseline\` (DAG Stage 3 — QA Hardening)."
    @echo "> Source: cargo-llvm-cov --workspace --all-features --json"
    @echo "> Threshold: 85% lines (matches \`just coverage-check\` and \`grade.sh\`)"
    @echo ""
    @echo "## Totals"
    @echo ""
    @echo "| Metric | Covered | Total | Percent |"
    @echo "|--------|---------|-------|---------|"
    @python3 -c "import json,sys; d=json.load(open('{{json_path}}')); t=d['data'][0]['totals']; lines=t['lines']; funcs=t['functions']; regions=t['regions']; print(f\"| Lines   | {lines['covered']} | {lines['count']} | {lines['percent']:.2f}% |\"); print(f\"| Funcs   | {funcs['covered']} | {funcs['count']} | {funcs['percent']:.2f}% |\"); print(f\"| Regions | {regions['covered']} | {regions['count']} | {regions['percent']:.2f}% |\")"
