//! Token — short opaque bearer-token generation and verification.

use std::fmt;

/// A 32-byte HMAC-SHA256 key for token signing.
#[derive(Clone)]
pub struct TokenKey(pub [u8; 32]);

impl TokenKey {
    /// Create a `TokenKey` from a slice, padding or truncating to 32 bytes.
    pub fn from_slice(seed: &[u8]) -> Self {
        let mut key = [0u8; 32];
        let copy_len = seed.len().min(32);
        key[..copy_len].copy_from_slice(&seed[..copy_len]);
        TokenKey(key)
    }
}

/// Generate a bearer token: 22 random bytes + HMAC-SHA256 tag.
/// Returns a hex-encoded 96-char string (44 hex + 64 hex).
pub fn mint(seed: &[u8]) -> String {
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    let mut rng = rand::thread_rng();
    use rand::RngCore;
    let mut payload = [0u8; 22];
    rng.fill_bytes(&mut payload);

    let key = TokenKey::from_slice(seed);
    let mut mac = Hmac::<Sha256>::new_from_slice(&key.0).expect("HMAC key");
    mac.update(&payload);
    let tag = mac.finalize().into_bytes();

    format!("{}{}", hex::encode(payload), hex::encode(tag))
}

/// Verify a token previously generated by [`mint`] with the same seed.
pub fn verify(token: &str, seed: &[u8]) -> bool {
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    if token.len() != 108 {
        return false;
    }
    let (payload_hex, tag_hex) = token.split_at(44);
    let payload = match hex::decode(payload_hex) {
        Ok(p) => p,
        Err(_) => return false,
    };
    let expected_tag = match hex::decode(tag_hex) {
        Ok(t) => t,
        Err(_) => return false,
    };

    let key = TokenKey::from_slice(seed);
    let mut mac = match Hmac::<Sha256>::new_from_slice(&key.0) {
        Ok(m) => m,
        Err(_) => return false,
    };
    mac.update(&payload);
    mac.verify_slice(&expected_tag).is_ok()
}

impl fmt::Display for TokenKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "TokenKey({} bytes)", self.0.len())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mint_and_verify_round_trip() {
        let seed = b"test-seed-123";
        let token = mint(seed);
        assert_eq!(token.len(), 108);
        assert!(verify(&token, seed));
    }

    #[test]
    fn reject_wrong_seed() {
        let token = mint(b"seed-a");
        assert!(!verify(&token, b"seed-b"));
    }

    #[test]
    fn reject_malformed_token() {
        assert!(!verify("short", b"seed"));
    }
}
