#!/usr/bin/env bash
# bootstrap.sh — OmniRoute dev environment fast-path (macOS zsh + Linux bash).
#
# Idempotent. Re-runnable. Designed for agent-driven dev loops:
#   - Detects Node/bun/npm; promotes the preferred package manager per repo
#   - Adds bun + node bins to PATH for the current shell + writes a marker for direnv
#   - Honors OMNI_SKIP_DEPS=1 / OMNI_FAST=1 for CI parity
#
# Usage:
#   ./scripts/bootstrap.sh                 # full bootstrap
#   OMNI_FAST=1 ./scripts/bootstrap.sh      # minimal (PATH only)
#   OMNI_SKIP_DEPS=1 ./scripts/bootstrap.sh # skip tool installs (CI)
#
# Note: OmniRoute prefers bun over npm (per package.json `packageManager` field
# convention). If bun is missing, installs via the official script; falls back to
# npm only when SKIP_DEPS=1 or bun install fails.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

log() { printf '\033[1;34m[bootstrap]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[bootstrap]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31m[bootstrap]\033[0m %s\n' "$*" >&2; exit 1; }

# ─── detect / install bun ─────────────────────────────────────────────────────
BUN_BIN="$HOME/.bun/bin"
mkdir -p "$BUN_BIN"
case ":$PATH:" in
  *":$BUN_BIN:"*) ;;
  *) export PATH="$BUN_BIN:$PATH" ;;
esac

# Persist for direnv / shells that re-source this file.
mkdir -p "$REPO_ROOT/.omni-bootstrap"
echo "$BUN_BIN" > "$REPO_ROOT/.omni-bootstrap/bun-bin"

if ! command -v bun >/dev/null 2>&1 && [[ "${OMNI_SKIP_DEPS:-0}" != "1" ]]; then
  log "bun not found — installing"
  if [[ "$(uname -s)" == "Darwin" ]] || [[ "$(uname -s)" == "Linux" ]]; then
    curl -fsSL https://bun.sh/install | bash
    # shellcheck disable=SC1091
    source "$BUN_BIN/env" 2>/dev/null || true
  elif [[ "$(uname -s)" == "MINGW"* ]] || [[ "$(uname -s)" == "CYGWIN"* ]]; then
    powershell -c "irm bun.sh/install.ps1 | iex"
  else
    die "unsupported platform: $(uname -s)"
  fi
fi

if command -v bun >/dev/null 2>&1; then
  log "bun: $(bun --version)"
else
  warn "bun not available — falling back to npm"
  command -v npm >/dev/null 2>&1 || die "neither bun nor npm available"
  log "npm: $(npm --version)"
fi

# ─── node sanity check ──────────────────────────────────────────────────────
command -v node >/dev/null 2>&1 || die "node not on PATH (required: >=22.0.0 <23 || >=24.0.0 <27)"
NODE_MAJOR="$(node --version | sed -E 's/^v([0-9]+).*/\1/')"
if (( NODE_MAJOR < 22 )) || { (( NODE_MAJOR == 23 )) || (( NODE_MAJOR >= 27 )); }; then
  warn "node version $(node --version) outside supported range (>=22.0.0 <23 || >=24.0.0 <27)"
fi
log "node: $(node --version)"

# ─── install deps (skippable) ────────────────────────────────────────────────
if [[ "${OMNI_SKIP_DEPS:-0}" != "1" && "${OMNI_FAST:-0}" != "1" ]]; then
  if command -v bun >/dev/null 2>&1; then
    log "bun install (workspace)"
    bun install || warn "bun install failed; continuing"
  else
    log "npm install"
    npm install --no-audit --no-fund || warn "npm install failed; continuing"
  fi
fi

# ─── write a hermetic env hint for subshells ─────────────────────────────────
cat > "$REPO_ROOT/.omni-bootstrap/env.sh" <<'ENV'
# auto-generated by bootstrap.sh — source this from your shell rc if not using direnv
export PATH="$HOME/.bun/bin:$PATH"
export OMNI_BOOTSTRAPPED=1
ENV

log "ok — OmniRoute dev env ready"
log "  run: just dev    (or bun run dev)"