# setup-windows.ps1 — OmniRoute dev environment fast-path (Windows PowerShell, non-WSL).
#
# Idempotent. Designed for agent-driven dev loops:
#   - Detects Node + bun; installs bun via the official PowerShell installer if missing
#   - Adds ~/.bun/bin to the persistent user PATH
#   - Honors OMNI_SKIP_DEPS / OMNI_FAST env vars for CI parity
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\scripts\setup-windows.ps1
#   $env:OMNI_FAST=1; powershell -ExecutionPolicy Bypass -File .\scripts\setup-windows.ps1
#
# Notes:
#   - Designed for non-WSL PowerShell. WSL users should use scripts/bootstrap.sh.
#   - Run from an elevated PowerShell when installing tools.

[CmdletBinding()]
param(
    [switch]$SkipDeps,
    [switch]$Fast
)

$ErrorActionPreference = 'Stop'

$RepoRoot = (Resolve-Path -Path (Join-Path $PSScriptRoot '..')).Path
Set-Location -LiteralPath $RepoRoot

function Write-Bootstrap([string]$msg, [string]$color = 'Cyan') {
    Write-Host "[bootstrap] $msg" -ForegroundColor $color
}

function Write-BootstrapWarn([string]$msg) {
    Write-Host "[bootstrap] $msg" -ForegroundColor Yellow
}

function Write-BootstrapErr([string]$msg) {
    Write-Host "[bootstrap] $msg" -ForegroundColor Red
}

# ─── bun bin on PATH ────────────────────────────────────────────────────────
$bunBin = Join-Path $env:USERPROFILE '.bun\bin'
if (-not (Test-Path $bunBin)) { New-Item -ItemType Directory -Path $bunBin -Force | Out-Null }

$userPath = [Environment]::GetEnvironmentVariable('PATH', 'User')
if ($userPath -notlike "*$bunBin*") {
    [Environment]::SetEnvironmentVariable('PATH', "$userPath;$bunBin", 'User')
    $env:PATH = "$env:PATH;$bunBin"
    Write-Bootstrap "added $bunBin to user PATH"
}

# ─── bun install ───────────────────────────────────────────────────────────
$skipDeps = $SkipDeps -or ($env:OMNI_SKIP_DEPS -eq '1')
$fast     = $Fast     -or ($env:OMNI_FAST     -eq '1')

if (-not $skipDeps) {
    if (-not (Get-Command bun -ErrorAction SilentlyContinue)) {
        Write-Bootstrap 'bun not found — installing via official PowerShell installer'
        try {
            Invoke-Expression (Invoke-WebRequest -Uri 'https://bun.sh/install.ps1' -UseBasicParsing).Content
        } catch {
            Write-BootstrapErr "bun install failed: $_"
            Write-BootstrapErr 'install bun manually from https://bun.sh'
            exit 1
        }
    } else {
        Write-Bootstrap 'bun already present'
    }
}

if (Get-Command bun -ErrorAction SilentlyContinue) {
    Write-Bootstrap ("bun: " + (bun --version))
} else {
    Write-BootstrapWarn 'bun unavailable — will fall back to npm'
    if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
        Write-BootstrapErr 'neither bun nor npm available'
        exit 1
    }
    Write-Bootstrap ("npm: " + (npm --version))
}

# ─── node sanity check ──────────────────────────────────────────────────────
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-BootstrapErr 'node not on PATH (required: >=22.0.0 <23 || >=24.0.0 <27)'
    exit 1
}
$nodeVersion = (node --version) -replace '^v', ''
$nodeMajor = [int]($nodeVersion -split '\.')[0]
if ($nodeMajor -lt 22 -or $nodeMajor -eq 23 -or $nodeMajor -ge 27) {
    Write-BootstrapWarn "node version $(node --version) outside supported range"
}
Write-Bootstrap ("node: " + (node --version))

# ─── install deps (skippable) ──────────────────────────────────────────────
if (-not $skipDeps -and -not $fast) {
    if (Get-Command bun -ErrorAction SilentlyContinue) {
        Write-Bootstrap 'bun install (workspace)'
        try { bun install } catch { Write-BootstrapWarn "bun install failed: $_" }
    } else {
        Write-Bootstrap 'npm install'
        try { npm install --no-audit --no-fund } catch { Write-BootstrapWarn "npm install failed: $_" }
    }
}

# ─── env marker for subshells ──────────────────────────────────────────────
$omniDir = Join-Path $RepoRoot '.omni-bootstrap'
if (-not (Test-Path $omniDir)) { New-Item -ItemType Directory -Path $omniDir -Force | Out-Null }
@(
    '# auto-generated by setup-windows.ps1',
    '$env:PATH = "$env:USERPROFILE\.bun\bin;$env:PATH"',
    '$env:OMNI_BOOTSTRAPPED = "1"'
) | Set-Content -LiteralPath (Join-Path $omniDir 'env.ps1') -Encoding UTF8

Write-Bootstrap 'ok — OmniRoute dev env ready' 'Green'
Write-Bootstrap '  run: just dev    (or bun run dev)'