#!/usr/bin/env bash
# scripts/ssot-inject.sh — L65 SSOT marker auto-inject
#
# Reads a file path, checks if its basename matches the SSOT pattern
# (WORKLOG.md, *.adr.md, AGENTS.md, SSOT.md, etc.), and prepends the
# canonical SSOT marker comment block if it is missing.
#
# Idempotent: re-running on a file that already has the marker is a no-op.
#
# Usage:
#   bash scripts/ssot-inject.sh <file> [<file> ...]
#   bash scripts/ssot-inject.sh --check <file>   # dry-run, exit 1 if missing
#   bash scripts/ssot-inject.sh --remove <file>  # strip an existing marker
#
# Exit codes:
#   0 — marker already present or successfully injected (no change needed)
#   1 — file does not match the SSOT pattern (skipped, nothing to do)
#   2 — file missing
#   3 — --check mode detected missing marker

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

MODE="inject"
if [ "${1:-}" = "--check" ] || [ "${1:-}" = "--remove" ]; then
    MODE="${1#--}"
    shift
fi

# ---------------------------------------------------------------------------
# Patterns that get the SSOT marker
# ---------------------------------------------------------------------------
# Match by basename (case-insensitive). The marker is a 6-line blockquote
# that points readers to SSOT.md and the relevant ADR section.
matches_ssot_pattern() {
    local base="$1"
    local lc
    lc=$(echo "$base" | tr '[:upper:]' '[:lower:]')
    case "$lc" in
        # Exact canonical names — match both bare and with any prefix.
        worklog.md|*worklog.md|*worklog-*.md)            return 0 ;;
        agents.md|*agents.md|*agents-*.md)               return 0 ;;
        ssot.md|*ssot.md|*ssot-*.md)                     return 0 ;;
        spec.md|*spec.md|*spec-*.md)                     return 0 ;;
        status.md|*status.md|*status-*.md)               return 0 ;;
        changelog.md|*changelog.md|*changelog-*.md)      return 0 ;;
        llms.txt|*llms.txt)                              return 0 ;;
        # *.adr.md — ADR documents; canonical naming is "NNNN-slug.adr.md"
        *.adr.md)                                        return 0 ;;
        *)
            return 1 ;;
    esac
}

# ---------------------------------------------------------------------------
# Marker template — must match the live convention used in fleet WORKLOG.md
# and AGENTS.md files. Keep this block small and stable.
# ---------------------------------------------------------------------------
SSOT_MARKER="# SSOT marker (L65) — see SSOT.md for cross-cutting authority.
# This file is a single-source-of-truth document. When this file conflicts
# with executable config (workflows, justfile, Cargo.toml), config wins.
# When it conflicts with other governance docs, see SSOT.md precedence order.
# Generated by scripts/ssot-inject.sh — idempotent (re-runs are no-ops).
"

# ---------------------------------------------------------------------------
# Detect whether the marker is already present (first 6 non-blank lines)
# ---------------------------------------------------------------------------
has_marker() {
    local file="$1"
    grep -q "^# SSOT marker (L65) — see SSOT.md for cross-cutting authority.$" "$file" 2>/dev/null
}

inject_marker() {
    local file="$1"
    if has_marker "$file"; then
        echo "ALREADY     $file"
        return 0
    fi
    local tmp
    tmp=$(mktemp)
    printf '%s' "$SSOT_MARKER" > "$tmp"
    cat "$file" >> "$tmp"
    mv "$tmp" "$file"
    echo "INJECTED    $file"
}

remove_marker() {
    local file="$1"
    if ! has_marker "$file"; then
        echo "ABSENT      $file"
        return 0
    fi
    # Strip the first 6 lines (the marker block).
    local tmp
    tmp=$(mktemp)
    tail -n +7 "$file" > "$tmp"
    mv "$tmp" "$file"
    echo "REMOVED     $file"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
if [ $# -lt 1 ]; then
    echo "usage: $0 [--check|--remove] <file> [<file> ...]" >&2
    exit 64
fi

RC=0
for raw in "$@"; do
    # Strip a leading "./" so the basename lookup is clean.
    path="${raw#./}"
    if [ ! -f "$path" ]; then
        echo "MISSING     $path" >&2
        RC=2
        continue
    fi
    base=$(basename "$path")
    if ! matches_ssot_pattern "$base"; then
        echo "SKIP        $path (does not match SSOT pattern)"
        continue
    fi
    case "$MODE" in
        inject)
            inject_marker "$path" || RC=1
            ;;
        check)
            if has_marker "$path"; then
                echo "OK          $path"
            else
                echo "MISSING     $path"
                RC=3
            fi
            ;;
        remove)
            remove_marker "$path" || RC=1
            ;;
    esac
done

exit $RC
