// Step-1 PR1: provider catalog — the "UNLIMITED_LLM_ACCESS" registry.
// All 22 providers enumerated; status is computed at startup by scanning
// the env / config file (no per-request work).
import type { ProviderDescriptor, ProviderId } from "./types.js";

const PROVIDERS: readonly ProviderDescriptor[] = [
  {
    id: "openai",
    kind: "api-key",
    label: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "OPENAI_API_KEY",
  },
  {
    id: "anthropic",
    kind: "api-key",
    label: "Anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    modelsEndpoint: "/v1/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "ANTHROPIC_API_KEY",
  },
  {
    id: "google",
    kind: "api-key",
    label: "Google AI (Gemini)",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "GOOGLE_API_KEY",
  },
  {
    id: "mistral",
    kind: "api-key",
    label: "Mistral AI",
    baseUrl: "https://api.mistral.ai/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "MISTRAL_API_KEY",
  },
  {
    id: "cohere",
    kind: "api-key",
    label: "Cohere",
    baseUrl: "https://api.cohere.ai/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: false,
    notes: "COHERE_API_KEY",
  },
  {
    id: "groq",
    kind: "api-key",
    label: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "GROQ_API_KEY (OpenAI-compatible)",
  },
  {
    id: "openrouter",
    kind: "api-key",
    label: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "OPENROUTER_API_KEY (OpenAI-compatible)",
  },
  {
    id: "together",
    kind: "api-key",
    label: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: false,
    notes: "TOGETHER_API_KEY",
  },
  {
    id: "fireworks",
    kind: "api-key",
    label: "Fireworks AI",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "FIREWORKS_API_KEY",
  },
  {
    id: "deepseek",
    kind: "api-key",
    label: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "DEEPSEEK_API_KEY",
  },
  {
    id: "xai",
    kind: "api-key",
    label: "xAI (Grok)",
    baseUrl: "https://api.x.ai/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "XAI_API_KEY",
  },
  {
    id: "perplexity",
    kind: "api-key",
    label: "Perplexity",
    baseUrl: "https://api.perplexity.ai",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: false,
    notes: "PERPLEXITY_API_KEY",
  },
  {
    id: "replicate",
    kind: "api-key",
    label: "Replicate",
    baseUrl: "https://api.replicate.com/v1",
    modelsEndpoint: "/models",
    supportsStreaming: false,
    supportsToolUse: false,
    notes: "REPLICATE_API_TOKEN",
  },
  {
    id: "bedrock",
    kind: "api-key",
    label: "AWS Bedrock",
    baseUrl: null,
    modelsEndpoint: null,
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY + AWS_REGION",
  },
  {
    id: "azure",
    kind: "api-key",
    label: "Azure OpenAI",
    baseUrl: null,
    modelsEndpoint: null,
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "AZURE_OPENAI_API_KEY + AZURE_OPENAI_ENDPOINT + AZURE_OPENAI_DEPLOYMENT",
  },
  {
    id: "vertex",
    kind: "api-key",
    label: "Google Vertex AI",
    baseUrl: null,
    modelsEndpoint: null,
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "GOOGLE_APPLICATION_CREDENTIALS + VERTEX_PROJECT",
  },
  {
    id: "github-models",
    kind: "api-key",
    label: "GitHub Models",
    baseUrl: "https://models.inference.ai.azure.com",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: false,
    notes: "GITHUB_TOKEN",
  },
  {
    id: "huggingface",
    kind: "api-key",
    label: "HuggingFace Inference",
    baseUrl: "https://api-inference.huggingface.co/models",
    modelsEndpoint: null,
    supportsStreaming: true,
    supportsToolUse: false,
    notes: "HF_TOKEN",
  },
  {
    id: "anyscale",
    kind: "api-key",
    label: "Anyscale Endpoints",
    baseUrl: "https://api.endpoints.anyscale.com/v1",
    modelsEndpoint: null,
    supportsStreaming: true,
    supportsToolUse: false,
    notes: "ANYSCALE_API_KEY",
  },
  {
    id: "deepinfra",
    kind: "api-key",
    label: "DeepInfra",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: false,
    notes: "DEEPINFRA_API_KEY",
  },
  {
    id: "zai",
    kind: "api-key",
    label: "Z.AI (GLM)",
    baseUrl: "https://api.z.ai/api/paas/v4",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "ZAI_API_KEY",
  },
  {
    id: "novita",
    kind: "api-key",
    label: "Novita AI",
    baseUrl: "https://api.novita.ai/v3/openai",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: false,
    notes: "NOVITA_API_KEY",
  },
  {
    id: "alibaba",
    kind: "api-key",
    label: "Alibaba Cloud (Qwen)",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    modelsEndpoint: "/models",
    supportsStreaming: true,
    supportsToolUse: true,
    notes: "DASHSCOPE_API_KEY (OpenAI-compatible)",
  },
] as const;

export function listProviders(): readonly ProviderDescriptor[] {
  return PROVIDERS;
}

export function getProvider(id: ProviderId): ProviderDescriptor | undefined {
  return PROVIDERS.find((p) => p.id === id);
}
